name: paynowuz
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

#environment:
  #sdk: ^3.5.3

environment:
    sdk: ">=3.5.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:


  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/AbyssinicaSIL-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

